export const dataDummy = [
  {
    label: "Data Prestasi",
    data: [
      { primary: "Januari", secondary: 73 },
      { primary: "Februari", secondary: 34 },
      { primary: "Maret", secondary: 37 },
      { primary: "April", secondary: 49 },
      { primary: "Mei", secondary: 40 },
      { primary: "Juni", secondary: 11 },
      { primary: "Juli", secondary: 25 },
      { primary: "Agustus", secondary: 2 },
      { primary: "September", secondary: 35 },
      { primary: "Oktober", secondary: 59 },
      { primary: "November", secondary: 59 },
      { primary: "Desember", secondary: 59 },
    ],
  },
  {
    label: "Info Mahasiswa",
    data: [
      { primary: "Januari", secondary: 70 },
      { primary: "Februari", secondary: 1 },
      { primary: "Maret", secondary: 100 },
      { primary: "April", secondary: 7 },
      { primary: "Mei", secondary: 65 },
      { primary: "Juni", secondary: 59 },
      { primary: "Juli", secondary: 39 },
      { primary: "Agustus", secondary: 74 },
      { primary: "September", secondary: 36 },
      { primary: "Oktober", secondary: 63 },
      { primary: "November", secondary: 59 },
      { primary: "Desember", secondary: 59 },
    ],
  },
  {
    label: "Penerimaan Mahasiswa",
    data: [
      { primary: "Januari", secondary: 80 },
      { primary: "Februari", secondary: 65 },
      { primary: "Maret", secondary: 35 },
      { primary: "April", secondary: 76 },
      { primary: "Mei", secondary: 56 },
      { primary: "Juni", secondary: 62 },
      { primary: "Juli", secondary: 8 },
      { primary: "Agustus", secondary: 92 },
      { primary: "September", secondary: 17 },
      { primary: "Oktober", secondary: 23 },
      { primary: "November", secondary: 59 },
      { primary: "Desember", secondary: 59 },
    ],
  },
  {
    label: "Gallery",
    data: [
      { primary: "Januari", secondary: 65 },
      { primary: "Februari", secondary: 89 },
      { primary: "April", secondary: 78 },
      { primary: "Maret", secondary: 24 },
      { primary: "Mei", secondary: 42 },
      { primary: "Juni", secondary: 72 },
      { primary: "Juli", secondary: 94 },
      { primary: "Agustus", secondary: 7 },
      { primary: "September", secondary: 79 },
      { primary: "Oktober", secondary: 50 },
      { primary: "November", secondary: 59 },
      { primary: "Desember", secondary: 59 },
    ],
  },
];
